image_xscale = 0;
image_yscale = 0;
image_angle = irandom_range(0, 359);
rot_spd = irandom_range(10, 20);
image_alpha = 0.7;
fade = 0;
scr_screenshake_light();
target_x = obj_mick.x;
target_y = obj_mick.y;
can_parry = 0;
