color = irandom_range(21, 26)
image_index = color
image_angle = irandom_range(0, 359)
image_speed = 0
sizeup = random_range(1, 6)
image_xscale = sizeup
image_yscale = sizeup
hspd = irandom_range(-20, 20)
vspd = irandom_range(-30, 0)
