if (global.right == 81)
    draw_text(x, y, "Q")
if (global.right == 87)
    draw_text(x, y, "W")
if (global.right == 69)
    draw_text(x, y, "E")
if (global.right == 82)
    draw_text(x, y, "R")
if (global.right == 84)
    draw_text(x, y, "T")
if (global.right == 89)
    draw_text(x, y, "Y")
if (global.right == 85)
    draw_text(x, y, "U")
if (global.right == 73)
    draw_text(x, y, "I")
if (global.right == 79)
    draw_text(x, y, "O")
if (global.right == 80)
    draw_text(x, y, "P")
if (global.right == 65)
    draw_text(x, y, "A")
if (global.right == 83)
    draw_text(x, y, "S")
if (global.right == 68)
    draw_text(x, y, "D")
if (global.right == 70)
    draw_text(x, y, "F")
if (global.right == 71)
    draw_text(x, y, "G")
if (global.right == 72)
    draw_text(x, y, "H")
if (global.right == 74)
    draw_text(x, y, "J")
if (global.right == 75)
    draw_text(x, y, "K")
if (global.right == 76)
    draw_text(x, y, "L")
if (global.right == 90)
    draw_text(x, y, "Z")
if (global.right == 88)
    draw_text(x, y, "X")
if (global.right == 67)
    draw_text(x, y, "C")
if (global.right == 86)
    draw_text(x, y, "V")
if (global.right == 66)
    draw_text(x, y, "B")
if (global.right == 78)
    draw_text(x, y, "N")
if (global.right == 77)
    draw_text(x, y, "M")
if (global.right == 48)
    draw_text(x, y, "0")
if (global.right == 49)
    draw_text(x, y, "1")
if (global.right == 50)
    draw_text(x, y, "2")
if (global.right == 51)
    draw_text(x, y, "3")
if (global.right == 52)
    draw_text(x, y, "4")
if (global.right == 53)
    draw_text(x, y, "5")
if (global.right == 54)
    draw_text(x, y, "6")
if (global.right == 55)
    draw_text(x, y, "7")
if (global.right == 56)
    draw_text(x, y, "8")
if (global.right == 57)
    draw_text(x, y, "9")
if (global.right == 39)
    draw_text(x, y, "right")
if (global.right == 39)
    draw_text(x, y, "RIGHT")
if (global.right == 38)
    draw_text(x, y, "UP")
if (global.right == 40)
    draw_text(x, y, "DOWN")
if (global.right == 13)
    draw_text(x, y, "ENTER")
if (global.right == 32)
    draw_text(x, y, "SPACE")
if (global.right == 160)
    draw_text(x, y, "right SHIFT")
if (global.right == 161)
    draw_text(x, y, "RIGHT SHIFT")
if (global.right == 162)
    draw_text(x, y, "right CTRL")
if (global.right == 163)
    draw_text(x, y, "RIGHT CTRL")
if (global.right == 164)
    draw_text(x, y, "right ALT")
if (global.right == 165)
    draw_text(x, y, "RIGHT ALT")
if (global.right == 8)
    draw_text(x, y, "BACKSPACE")
if (global.right == 9)
    draw_text(x, y, "TAB")
if (global.right == 36)
    draw_text(x, y, "HOME")
if (global.right == 35)
    draw_text(x, y, "END")
if (global.right == 46)
    draw_text(x, y, "DELETE")
if (global.right == 45)
    draw_text(x, y, "INSERT")
if (global.right == 33)
    draw_text(x, y, "PAGE UP")
if (global.right == 34)
    draw_text(x, y, "PAGE DOWN")
if (global.right == 19)
    draw_text(x, y, "PAUSE")
if (global.right == 44)
    draw_text(x, y, "PRINT SCREEN")
if (global.right == 112)
    draw_text(x, y, "F1")
if (global.right == 113)
    draw_text(x, y, "F2")
if (global.right == 114)
    draw_text(x, y, "F3")
if (global.right == 115)
    draw_text(x, y, "F4")
if (global.right == 116)
    draw_text(x, y, "F5")
if (global.right == 117)
    draw_text(x, y, "F6")
if (global.right == 118)
    draw_text(x, y, "F7")
if (global.right == 119)
    draw_text(x, y, "F8")
if (global.right == 120)
    draw_text(x, y, "F9")
if (global.right == 121)
    draw_text(x, y, "F10")
if (global.right == 122)
    draw_text(x, y, "F11")
if (global.right == 123)
    draw_text(x, y, "F12")
if (global.right == 96)
    draw_text(x, y, "NUMPAD 0")
if (global.right == 97)
    draw_text(x, y, "NUMPAD 1")
if (global.right == 98)
    draw_text(x, y, "NUMPAD 2")
if (global.right == 99)
    draw_text(x, y, "NUMPAD 3")
if (global.right == 100)
    draw_text(x, y, "NUMPAD 4")
if (global.right == 101)
    draw_text(x, y, "NUMPAD 5")
if (global.right == 102)
    draw_text(x, y, "NUMPAD 6")
if (global.right == 103)
    draw_text(x, y, "NUMPAD 7")
if (global.right == 104)
    draw_text(x, y, "NUMPAD 8")
if (global.right == 105)
    draw_text(x, y, "NUMPAD 9")
if (global.right == 106)
    draw_text(x, y, "MULTIPLY")
if (global.right == 111)
    draw_text(x, y, "DIVIDE")
if (global.right == 107)
    draw_text(x, y, "ADD")
if (global.right == 109)
    draw_text(x, y, "SUBTRACT")
if (global.right == 110)
    draw_text(x, y, "DECIMAL")
if (global.right == 192)
    draw_text(x, y, "TILDE")
if (global.right == 189)
    draw_text(x, y, "MINUS")
if (global.right == 187)
    draw_text(x, y, "EQUALS")
if (global.right == 219)
    draw_text(x, y, "OPEN BRACKET")
if (global.right == 221)
    draw_text(x, y, "CLOSED BRACKET")
if (global.right == 220)
    draw_text(x, y, "BACKSLASH")
if (global.right == 20)
    draw_text(x, y, "CAPS LOCK")
if (global.right == 186)
    draw_text(x, y, "SEMICOLON")
if (global.right == 222)
    draw_text(x, y, "APOSTROPHE")
if (global.right == 188)
    draw_text(x, y, "COMMA")
if (global.right == 190)
    draw_text(x, y, "PERIOD")
if (global.right == 191)
    draw_text(x, y, "SLASH")
